config/routes.rb
Rails.application.routes.draw do
  root 'sessions#welcome'
  resources :users, only: [:new, :create, :show]
  resources :events do
    post 'attend', on: :member
  end
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'
  get '/welcome' => 'sessions#welcome'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :attendee, class_name: :User
  belongs_to :attended_event, class_name: :Event
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :attendances, foreign_key: :attended_event_id
  has_many :attendees, through: :attendances, source: :attendee
  belongs_to :creator, class_name: :User, foreign_key: :creator_id
  validates :title, presence: true
  validates :description, presence: true
  validates :event_date, presence: true
  scope :all_upcoming_events, -> { where('event_date > ?', Time.now) }
  scope :all_past_events, -> { where('event_date < ?', Time.now) }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :attendances, foreign_key: :attendee_id
  has_many :attended_events, through: :attendances, source: :attended_event
  has_many :created_events, foreign_key: :creator_id, class_name: :Event
  validates :full_name, presence: true
  validates :username, presence: true
  validates :email, presence: true
  def upcoming_events
    attended_events.select { |t| t.event_date.to_s > Time.now.to_s }
  end

  def previous_events
    attended_events.select { |t| t.event_date.to_s < Time.now.to_s }
  end

  def upcoming_created_events
    created_events.select { |t| t.event_date.to_s > Time.now.to_s }
  end

  def previous_created_events
    created_events.select { |t| t.event_date.to_s < Time.now.to_s }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  helper_method :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.all
    @all_upcoming_events = Event.all_upcoming_events
    @all_past_events = Event.all_past_events
  end

  def new
    @event = Event.new
  end

  def show
    @event = Event.find(params[:id])
  end

  def create
    @user = current_user
    @event = @user.created_events.build(event_params)
    if @event.save
      flash.notice = 'Event created successfully'
      redirect_to @user
    else
      flash[:notice] = 'Something went wrong'
      render 'new'
    end
  end

  def attend
    @event = Event.find(params[:id])
    current_user.attended_events << @event
    redirect_to @event
  end

  private

  def event_params
    params.require(:event).permit(:title, :description, :event_date)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    @user = User.find_by(username: params[:login][:username])

    if @user
      flash.notice = 'You have logged in successfully'
      session[:user_id] = @user.id.to_s
      session[:username] = @user.username
      redirect_to @user
    else
      flash.notice = 'Login failed. Something went wrong'
      redirect_to '/login'
    end
  end

  def destroy
    session.delete(:user_id)
    session.delete(:username)
    flash.notice = 'You have logged out successfully'
    @current_user = nil
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    if session[:username].nil?
      @user = User.new
    else
      @user = User.find(session[:id])
      redirect_to user_path(@user)
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "Profile for #{@user.full_name} Created successfully"
      session[:user_id] = @user.id.to_s
      session[:username] = @user.username
      redirect_to user_path(@user)
    else
      flash[:notice] = 'Something went wrong'
      render('new')
    end
  end

  def show
    @user = User.find(params[:id])
    @created_events = @user.created_events
    @upcoming_events = @user.upcoming_created_events
    @previous_events = @user.previous_created_events
  end

  def destroy
    session.delete(:id)
    @current_user = nil
  end

  private

  def user_params
    params.require(:user).permit(:full_name, :username, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendance_helper.rb
module AttendanceHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user?
    !session[:username].nil?
  end

  def current_user
    return unless (user_id = session[:id])

    @current_user ||= User.find(user_id)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/index.html.erb
<h3>List of All Events</h3>
<table class="table">
  <thead>
    <tr>
      <th>Event name</th>
      <th>Description</th>
      <th>Event Date</th>
      <th>Event Creator</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr><% @events.each do |e| %></tr>
      <td><%= e.title %></td>
      <td><%= e.description %></td>
      <td><%= e.event_date %></td>
      <td><%= e.creator.username %></td>
      <td><%= link_to "Show details", event_path(e) %></td>
    <% end %>
 </tbody>
</table>

<div class="container">
  <h3>All upcoming Events</h3>
  <table class="table">
    <thead>
      <tr>
        <th>Event name</th>
        <th>Description</th>
        <th>Event Date</th>
        <th>Event Creator</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <tr><% @all_upcoming_events.each do |e| %></tr>
        <td><%= e.title %></td>
        <td><%= e.description %></td>
        <td><%= e.event_date %></td>
        <td><%= e.creator.username %></td>
        <td><%= link_to "Show details", event_path(e) %></td>
      <% end %>
    </tbody>
  </table>

  <h3>All past events</h3>
  <table class="table">
    <thead>
      <tr>
        <th>Event title</th>
        <th>Description</th>
        <th>Event Date</th>
        <th>Event Creator</th>
      </tr>
    </thead>
    <tbody>
      <tr><% @all_past_events.each do |e| %></tr>
        <td><%= e.title %></td>
        <td><%= e.description %></td>
        <td><%= e.event_date %></td>
        <td><%= e.creator.username %></td>
        <td><%= link_to "Show details", event_path(e) %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/events/new.html.erb
<h1>Create Event</h1>

<%= form_for @event do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div><br/>
  <div>
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div><br/>
  <div>
    <%= f.label :event_date %>
    <%= f.date_field :event_date %>
  </div><br/>
  <div>
    <%= f.submit "Create Event" %>
  </div>
<% end %>

app/views/events/show.html.erb
<h3>Title: <%= @event.title %></h3>
<p><strong>Event date: </strong><%= @event.event_date %></p>
<p><strong>Description: </strong><%= @event.description %></p>

<% if @event.attendees.empty? %>
  <p>No attandees</p>
<% else %>
  <strong>Attendees:</strong>
  <ul>
    <% @event.attendees.each do |attendee| %>
      <li><%= link_to attendee.full_name, user_path(attendee.id) %></li>
    <% end %>
  </ul>
<% end %>

<%= link_to 'Event To Attend', attend_event_path(@event), method: :post %>

app/views/layouts/_header.html.erb
<% if current_user == nil && !current_user? %>
  <%= link_to "Home", '/welcome' %>
<% end %>
<% if current_user? %>
  <%= link_to "All events", events_path %>
  <%= link_to "New event", new_event_path %>
  <%= link_to "You Signed in with username #{current_user.username}", user_path(current_user) %>
  <%= link_to "Log Out", '/logout', method: :delete %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/header' %>
    <p class="flash"><%= flash.notice %></p>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  Username: <%= f.text_field :username %><br />
  Password : <%= f.password_field :password %><br />
  <%= f.submit "Create" %>
<% end %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= form_with(model: @user, local: true) do |f| %>
  <div>
    <%= f.label :full_name %><br />
    <%= f.text_field :full_name, placeholder: "Enter your full name" %>
  </div>
  <div>
    <%= f.label :username %><br />
    <%= f.text_field :username, placeholder: "Enter your username" %>
  </div>
  <div>
     <%= f.label :email %><br />
     <%= f.text_field :email , placeholder: "Your email" %>
  </div>

  <div class="action">
    <%= f.submit 'Sign Up' %>
  </div>
<% end %>

app/views/users/show.html.erb
<h3>User profile page for: <%= @user.full_name if @user %></h3>
  <div class="container">
  <p>Created events: </p>
  <table class="table">
    <thead>
      <tr>
        <th>Event name</th>
        <th>Description</th>
        <th>Event Date</th>
      </tr>
    </thead>
    <tbody>
        <tr><% @created_events.each do |e| %></tr>
          <td><%= e.title %></td>
          <td><%= e.description %></td>
          <td><%= e.event_date %></td>
          <% end %>
    </tbody>
  </table>
  <p>Upcoming events:</p>
    <table class="table">
      <thead>
        <tr>
          <th>Event name</th>
          <th>Description</th>
          <th>Event Date</th>
        </tr>
      </thead>
      <tbody>
          <tr><% @upcoming_events.each do |e| %></tr>
            <td><%= e.title %></td>
            <td><%= e.description %></td>
            <td><%= e.event_date %></td>
          <% end %>
      </tbody>
    </table>
  <p>Previous events: </p>
    <table class="table">
      <thead>
        <tr>
          <th>Event name</th>
          <th>Place</th>
          <th>Event Date</th>
        </tr>
      </thead>
      <tbody>
          <tr><% @previous_events.each do |e| %></tr>
            <td><%= e.title %></td>
            <td><%= e.description %></td>
            <td><%= e.event_date %></td>
          <% end %>
      </tbody>
    </table>
</div>